development:
  adapter: postgresql
  database: bap_dev
  host: localhost
  pool: 5
  timeout: 6000
  username: trust
  password: trust  

test: &test
  adapter: postgresql
  database: bap_test
  pool: 5
  timeout: 6000
  username: trust
  password: trust  

production:
  adapter: postgresql
  database: bap_production
  pool: 5
  timeout: 6000
  username: trust
  password: trust  
